### ISSUE TITLE
Streaming IO versus objects

### ISSUE THREAD

**Issue by pmackay** [nevern02/rodimus#4]
I'm not an ETL expert, so please read this with that in mind :)

The use case I'm looking at is:
* pull some data from an API
* parse the response into JSON
* manipulate the data so its a different JSON structure
* save the data into a collection CSV files

I understand the IO based design of Rodimus, but wondering if you've encountered a situation where it would make more sense to pass objects or hashes around rather than needing to convert to streamable data. Or is there a pattern how this might be done with Rodimus currently? It feels like every step needs to do conversions between strings and JSON. 

Note: the data is small so performance is not an issue, and converting is only a couple of lines, I'm more just interested in if this was ever a consideration.

Much appreciate any comments!

**Comment by nevern02** [comment]
Don't worry, I'm not an ETL expert either.  I was thrown into the world of ETL and data warehousing without any warning, and I've kind of had to learn along the way.  

The format of the data that passes between steps is pretty flexible.  I just use JSON because it's convenient when working with Ruby.  Because the data is passed from step to step via pipes, whatever format you use has to be some that's serialized for the communication process.  We're communicating between processes here, not threads, so there's no shared memory between steps during the transformation process.  

This was an intentional design decision because: 1) I wanted true parallelism between steps.  I routinely perform ETL operations on data sets that are millions of rows, so I need it to be reasonable fast.  And 2) I would eventually like to experiment with distributing transformations across machines, and this method of inter-process communication can be easily swapped out for plain old sockets or something.

So yes, for small data sets, using Rodimus to transform the data may be overkill.  But the larger your ETL operation, the more sense it makes to use something like this.  The overhead of serializing/de-serializing to/from JSON is pretty negligible as a trade-off for the power of parallelism.
